Traceback (most recent call last):
  File "/Users/hemapillay/MyPythonScripts/raiseAndAssertExceptions.py", line 4, in <module>
    raise Exception('This is error message.')
Exception: This is error message.
